Style use scss for project E-Shop
st-quangtran/FE-Internship-2021_Quang-Tran-M_FE-Exercise pull request #14
Opened 2021-04-23 09:56 UTC by st-quangtran

- Use scss for project E-Shop

2021-04-23 10:25 UTC, st-dungnguyen requested changes

2021-04-23 10:25 UTC, st-dungnguyen commented on exercise_e_shop/assets/stylesheet/base/_common.scss
> +	font-family: "Poppins", sans-serif;
Lỗi indent. Lỗi cơ bản, check lại cho tất cả các files

2021-04-23 10:25 UTC, st-dungnguyen commented on exercise_e_shop/assets/stylesheet/modules/_all.scss
> +@import 'text-uppercase';
thiếu endline. Lỗi cơ bản

2021-04-23 10:25 UTC, st-dungnguyen commented on exercise_e_shop/home.html
> +          <h3 class="section-title text-center title-benefit">Why should you choose us?</h3>
`title-benefit` không dùng

2021-04-23 10:25 UTC, st-dungnguyen commented on exercise_e_shop/home.html
> +          <h3 class="section-title text-center title-today">Products in today</h3>
`title-today` dư thừa

2021-04-25 15:26 UTC, st-dieple commented on exercise_e_shop/assets/stylesheet/base/_grid.scss
> +  margin: -6px -10px;
Không set margin top/bottom trực tiếp cho row. Default là `margin: 0 -10px;`
Để tạo khoảng cách giữa các row, sử dụng selector `.row + .row` và set margin top

2021-04-25 15:26 UTC, st-dieple commented on exercise_e_shop/assets/stylesheet/base/_variables.scss
> +  rd: #FF0000,
Đặt tên biến rõ ràng. Không viết tắt.

2021-04-25 15:26 UTC, st-dieple commented on exercise_e_shop/assets/stylesheet/base/_variables.scss
> +  xs: 13px,
`xs` sẽ là size nhỏ hơn `s` nha.

2021-04-25 15:26 UTC, st-dieple commented on exercise_e_shop/assets/stylesheet/base/_variables.scss
> +  xxxxxxl: 72px,
Thay vì dùng quá nhiều chữ `xxxx` thì có thể xem xét đổi qua số cho ngắn gọn và dễ đọc: `4xl`, `5xl`,...

2021-04-25 15:26 UTC, st-dieple commented on exercise_e_shop/assets/stylesheet/base/_variables.scss
> +$lg: 1024px;
Dư biến rồi e

2021-04-25 17:00 UTC, st-dieple commented
@st-quangtran Sửa lại dòng này:
https://github.com/st-quangtran/FE-Internship-2021_Quang-Tran-M_FE-Exercise/blob/a1f366b3ba6658cc11ca8d981a239c3eeb4b7543/exercise_e_shop/home.html#L104

Dư thẻ section bọc ngoài.

2021-04-26 06:41 UTC, merged