Exercise/20210407 quang html
st-quangtran/FE-Internship-2021_Quang-Tran-M_FE-Exercise pull request #6
Opened 2021-04-08 02:31 UTC by st-quangtran

-Description:
Tao layout cho trang homepage, dat ten class.

-Reference:
#4 
#5

2021-04-08 18:10 UTC, st-dieple commented on exercise_html/home.html
> +  <header class="my-header">
ko dùng `my`, ví dụ sau này làm dự án, code không phải chỉ của riêng mình
có thể dùng `page-header`

2021-04-08 18:10 UTC, st-dieple commented on exercise_html/home.html
> +    <div>
dư thẻ div

2021-04-08 18:10 UTC, st-dieple commented on exercise_html/home.html
> +    <section class="section section1">
đặt tên class theo đúng vai trò, không đặt kiểu `abc-1`, `abc-2`

2021-04-08 18:10 UTC, st-dieple commented on exercise_html/home.html
> +      <div class="section1">
tên class không rõ ràng. Đổi tên đúng với vai trò của từng phần

2021-04-08 18:10 UTC, st-dieple commented on exercise_html/home.html
> +        <ul class="ul ul-list-item">
1. không cần class ul
2. tên class không rõ ràng, ko biết `ul-list` là list gì 🤔
3. thẻ `<ul>` là cả list, ko phải một item trong list

2021-04-08 18:10 UTC, st-dieple commented on exercise_html/home.html
> +          <li class="li li-item">
1. Tương tụ ở trên, ko cần class li
2.  Tên class không rõ ràng, ko biết `li-item` là item của list gì

2021-04-08 18:10 UTC, st-dieple commented on exercise_html/home.html
> +  <footer class="my-footer">
tương tự header

2021-04-09 06:50 UTC, st-dungnguyen commented on exercise_html/home.html
> +	</main>
lỗi căn lề

2021-04-09 06:50 UTC, st-dungnguyen commented on exercise_html/home.html
> +    <div class="header-left">
Thiếu thẻ `<div class="container">` bọc tất cả element trong header

2021-04-09 06:50 UTC, st-dungnguyen commented on exercise_html/home.html
> +  <footer class="page-footer">
Thêm `<div class="container">` bọc tất cả element trong footer

2021-04-09 09:13 UTC, st-dungnguyen requested changes

2021-04-09 09:13 UTC, st-dungnguyen commented on exercise_html/home.html
> +          <select class="select">
nên đặt tên class rõ hơn. không nên đặt trùng tên thẻ.
ví dụ `<select class="sort">`

2021-04-09 09:13 UTC, st-dungnguyen commented on exercise_html/home.html
> +            <option class="option">Useless firse</option>
`<option>` phải có value

2021-04-12 01:15 UTC, st-dungnguyen commented
LGTM!

2021-04-12 01:16 UTC, merged